export default {
    weapons: [
        {
            id: 'wooden_sword',
            name: 'Wooden Sword',
            description: 'A basic wooden sword. Better than nothing.',
            price: 25,
            damage: 2,
            icon: 'sword',
            rarity: 'common',
        },
        {
            id: 'iron_sword',
            name: 'Iron Sword',
            description: 'A sturdy iron sword. Reliable and effective.',
            price: 60,
            damage: 5,
            icon: 'swords',
            rarity: 'common',
        },
        {
            id: 'steel_blade',
            name: 'Steel Blade',
            description: 'A sharp steel blade. Cuts through armor.',
            price: 120,
            damage: 8,
            icon: 'crosshair',
            rarity: 'uncommon',
        },
        {
            id: 'flame_sword',
            name: 'Flame Sword',
            description: 'A sword imbued with fire magic. Burns enemies.',
            price: 250,
            damage: 12,
            icon: 'flame',
            rarity: 'rare',
        },
        {
            id: 'dragon_slayer',
            name: 'Dragon Slayer',
            description: 'Legendary sword that can slay dragons.',
            price: 500,
            damage: 20,
            icon: 'crown',
            rarity: 'legendary',
        },
    ],
    consumables: [
        {
            id: 'teleport_scroll',
            name: 'Teleport Scroll',
            description: 'Instantly teleport back home, escaping the dungeon.',
            price: 75,
            icon: 'scroll-text',
            rarity: 'uncommon',
            consumable: true,
            action: 'teleport_exit',
        },
    ],
    armor: [
        {
            id: 'leather_armor',
            name: 'Leather Armor',
            description: 'Basic leather protection. Light and flexible.',
            price: 20,
            defense: 2,
            icon: 'shield',
            rarity: 'common',
        },
        {
            id: 'chain_mail',
            name: 'Chain Mail',
            description: 'Interlocked metal rings. Good protection.',
            price: 50,
            defense: 5,
            icon: 'link',
            rarity: 'common',
        },
        {
            id: 'plate_armor',
            name: 'Plate Armor',
            description: 'Heavy metal plates. Excellent defense.',
            price: 100,
            defense: 8,
            icon: 'shield-check',
            rarity: 'uncommon',
        },
        {
            id: 'magic_robe',
            name: 'Magic Robe',
            description: 'Enchanted robe that deflects spells.',
            price: 200,
            defense: 12,
            icon: 'sparkles',
            rarity: 'rare',
        },
        {
            id: 'divine_armor',
            name: 'Divine Armor',
            description: 'Blessed armor with divine protection.',
            price: 400,
            defense: 18,
            icon: 'shield-check',
            rarity: 'legendary',
        },
    ],
};
