name: Deploy to GitHub Pages

on:
    workflow_dispatch:
    push:
        branches: ['**']
        paths: ['documentation/**', 'build-docs.sh', 'project/**']

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      documentation
                      project
                      build-docs.sh
                  sparse-checkout-cone-mode: false

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Cache pandoc
              uses: actions/cache@v4
              with:
                  path: /var/lib/apt/lists
                  key: ${{ runner.os }}-pandoc-${{ hashFiles('.github/workflows/documentation.yml') }}

            - name: Install pandoc
              run: |
                  sudo apt-get update
                  sudo apt-get install -y pandoc

            - name: Build docs
              run: ./build-docs.sh

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: 'dist'

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
